name:                audaxian-toolbox
version:             0.1.0.0
github:              "githubuser/audaxian-toolbox"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/audaxian-toolbox#readme>

dependencies:
- aeson >= 1.3
- amazonka >= 1.6
- amazonka-s3 >= 1.6
- base >= 4.7 && < 5
- bytestring >= 0.10
- conduit >= 1.3
- conduit-extra >= 1.3
- lens >= 4.16
- monad-logger
- mtl >= 2.2
- optparse-applicative
- pretty-show >= 1.6
- resourcet >= 1.2
- text >= 1.2
- unliftio >= 0.2.7
- unliftio-core >= 0.1.2
- uuid
- yaml

library:
  source-dirs: src

tests:
  audaxian-toolbox-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - audaxian-toolbox
    - hspec
